version: "3.1"
services:

    unpleasant:
      container_name: unpleasant
      image: myflaskapp:1.0.0
      build: .
      ports:
        - 5000:5000
      depends_on:
        - unpleasant_db


    unpleasant_db:
      container_name: unpleasant_db
      image: postgres:13
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: unpleasant_db
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }
