version: "3.1"
services:

    flaskapp:
      container_name: flaskapp
      image: myflaskapp:1.0.0
      build: .
      ports:
        - 5000:5000
      depends_on:
        - flask_db


    flask_db:
      container_name: flask_db
      image: postgres:13
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: flask_test
      ports:
        - 5432:5432
      volumes:
        - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: { }
